/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ncirl.oop.groupca.alex.util;
import com.ncirl.oop.groupca.OOPGroupCAGUI;
import com.ncirl.oop.groupca.thomas.enums.TruckStyle;
import com.ncirl.oop.groupca.thomas.shared.CustomisationManager;
import com.ncirl.oop.groupca.thomas.shared.ScoreManager;
import java.util.Arrays;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
/**
 *
 * @author Alex + Thomas
 */
public class CustomisationGUI extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomisationGUI.class.getName());
   
    /**
     * Creates new form CustomisationGUI
     */
    private boolean itemsAdded = false;
    
    private static ComboBoxModel<String> getTruckStyleList() {
        String[] itemNamesList = Arrays.stream(TruckStyle.values())
                .map(TruckStyle::toString)
                .toArray(String[]::new);
        return new DefaultComboBoxModel<>(itemNamesList);
    }
    
    public CustomisationGUI() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new java.awt.Label();
        hatCmb = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();
        hatLbl = new javax.swing.JLabel();
        shirtLbl = new javax.swing.JLabel();
        shirtCmb = new javax.swing.JComboBox<>();
        truckCmb = new javax.swing.JComboBox<>();
        truckLbl = new javax.swing.JLabel();
        resetCustomisationsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setText("Customise your character!");

        hatCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Top Hat", "Straw Hat", "Propeller Hat", "Delivery Hat" }));
        hatCmb.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                hatCmbHierarchyChanged(evt);
            }
        });
        hatCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hatCmbActionPerformed(evt);
            }
        });

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_icons/back.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        hatLbl.setText("Select a hat!");

        shirtLbl.setText("Select a shirt colour!");

        shirtCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Cyan", "Red", "Magenta", "Pink", "Gray", "Black" }));
        shirtCmb.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                shirtCmbHierarchyChanged(evt);
            }
        });
        shirtCmb.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                shirtCmbAncestorRemoved(evt);
            }
        });
        shirtCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shirtCmbActionPerformed(evt);
            }
        });

        truckCmb.setModel(getTruckStyleList());
        truckCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truckCmbActionPerformed(evt);
            }
        });

        truckLbl.setText("Select a truck style!");

        resetCustomisationsBtn.setText("Reset Customisations");
        resetCustomisationsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCustomisationsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetCustomisationsBtn)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hatCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hatLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shirtCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shirtLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(truckCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(truckLbl)))
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(43, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shirtLbl)
                    .addComponent(truckLbl)
                    .addComponent(hatLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hatCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shirtCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(truckCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(resetCustomisationsBtn))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hatCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hatCmbActionPerformed
        JComboBox comboBox = (JComboBox) evt.getSource();
        switch((String)comboBox.getSelectedItem()) { // Transfers hat choice to Customisation Manager
            case "Top Hat":
                CustomisationManager.setHat(1);
                break;
            case "Straw Hat":
                CustomisationManager.setHat(2);
                break;
            case "Propeller Hat":
                CustomisationManager.setHat(3);
                break;
            case "Delivery Hat":
                CustomisationManager.setHat(4);
                break; 
            case "Cowboy Hat":
                CustomisationManager.setHat(5);
                break;
            case "Cowboy Hat (800 points)":
                JOptionPane.showMessageDialog(null, "You do not have enough points to use this item.");
                break;
            case "Pirate Hat":
                CustomisationManager.setHat(6);
                break;
            case "Pirate Hat (1000 points)":
                JOptionPane.showMessageDialog(null, "You do not have enough points to use this item.");
                break;
        }      
    }//GEN-LAST:event_hatCmbActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        OOPGroupCAGUI mainMenuGUI = new OOPGroupCAGUI(); // Back button functionality
        mainMenuGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void hatCmbHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_hatCmbHierarchyChanged
        JComboBox comboBox = (JComboBox) evt.getSource(); // Load saved choice of hat to customisations dropdown
        if(!itemsAdded) {
            if(ScoreManager.getTotalScore()>=800) {
                comboBox.addItem("Cowboy Hat");
            } else {
                comboBox.addItem("Cowboy Hat (800 points)");
            }
            if(ScoreManager.getTotalScore()>=1000) {
                comboBox.addItem("Pirate Hat");
            } else {
                comboBox.addItem("Pirate Hat (1000 points)");
            }
            itemsAdded=true;
        }
        comboBox.setSelectedIndex(CustomisationManager.getHat());
    }//GEN-LAST:event_hatCmbHierarchyChanged

    private void shirtCmbHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_shirtCmbHierarchyChanged
        JComboBox comboBox = (JComboBox) evt.getSource(); // Load saved choice of shirt to customisations dropdown
        comboBox.setSelectedIndex(CustomisationManager.getBodyNum());
    }//GEN-LAST:event_shirtCmbHierarchyChanged

    private void shirtCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shirtCmbActionPerformed
        JComboBox comboBox = (JComboBox) evt.getSource(); // Sends shirt choice to customisations manager
        CustomisationManager.setBody(comboBox.getSelectedIndex());
    }//GEN-LAST:event_shirtCmbActionPerformed

    private void resetCustomisationsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCustomisationsBtnActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(this, "Are you sure you want to reset all your customizations?", "Reset Customisations", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirmed == 0) {
            CustomisationManager.resetCustomisations();
            
            dispose();
            CustomisationGUI menu = new CustomisationGUI();
            menu.setVisible(true);
        }
    }//GEN-LAST:event_resetCustomisationsBtnActionPerformed

    private void shirtCmbAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_shirtCmbAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_shirtCmbAncestorRemoved

    private void truckCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truckCmbActionPerformed
        String selectedStyle = (String) truckCmb.getSelectedItem();
        
        switch (selectedStyle) {
            case "Default":
                CustomisationManager.setTruckStyle(0);
                break;
            case "Christmas":
                CustomisationManager.setTruckStyle(1);
                break;
            case "Golden (900 points)":
                if (ScoreManager.getTotalScore() >= 900) {
                    CustomisationManager.setTruckStyle(2);
                } else {
                    JOptionPane.showMessageDialog(this, "You do not have enough points to use this item.");
                    truckCmb.setSelectedIndex(0);
                }
                break;
            default:
                // This shouldn't be triggered, but is required to prevent errors.
                JOptionPane.showMessageDialog(this, "Invalid option");
                break;
        }
    }//GEN-LAST:event_truckCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomisationGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> hatCmb;
    private javax.swing.JLabel hatLbl;
    private javax.swing.JButton resetCustomisationsBtn;
    private javax.swing.JComboBox<String> shirtCmb;
    private javax.swing.JLabel shirtLbl;
    private java.awt.Label titleLbl;
    private javax.swing.JComboBox<String> truckCmb;
    private javax.swing.JLabel truckLbl;
    // End of variables declaration//GEN-END:variables
}
