/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ncirl.oop.groupca.thomas.ScoreWindow;

import com.ncirl.oop.groupca.OOPGroupCAGUI;
import com.ncirl.oop.groupca.alex.util.Scores;
import com.ncirl.oop.groupca.alex.util.FileLoader;
import com.ncirl.oop.groupca.thomas.shared.ScoreManager;

import javax.swing.JOptionPane;

/**
 *
 * @author tom
 */
public class ScoreGUI extends javax.swing.JFrame {
    private final Scores scores = ScoreManager.getInstance();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ScoreGUI.class.getName());

    /**
     * Creates new form ScoreGUI
     */
    public ScoreGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        growScoreLbl = new javax.swing.JLabel();
        deliverScoreLbl = new javax.swing.JLabel();
        manageScoreLbl = new javax.swing.JLabel();
        resetScoreBtn = new javax.swing.JButton();
        totalScoreLbl = new javax.swing.JLabel();
        dogImageLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_icons/back.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        titleLbl.setText("Your Score");

        growScoreLbl.setText(scores.getAlexScoreText());

        deliverScoreLbl.setText(scores.getAntonioScoreText());

        manageScoreLbl.setText(scores.getThomasScoreText());

        resetScoreBtn.setText("Reset Score");
        resetScoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetScoreBtnActionPerformed(evt);
            }
        });

        totalScoreLbl.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        totalScoreLbl.setText(scores.getFullScoreText());

        dogImageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dog_thumbs_up_scaled.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetScoreBtn)
                            .addComponent(totalScoreLbl)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(growScoreLbl)
                            .addComponent(deliverScoreLbl)
                            .addComponent(manageScoreLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(dogImageLbl)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(growScoreLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deliverScoreLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manageScoreLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalScoreLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(resetScoreBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dogImageLbl)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        OOPGroupCAGUI mainMenuGUI = new OOPGroupCAGUI();
        mainMenuGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void resetScoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetScoreBtnActionPerformed
        JOptionPane.showConfirmDialog(this, "Are you sure you want to reset your score?");
    }//GEN-LAST:event_resetScoreBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ScoreGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel deliverScoreLbl;
    private javax.swing.JLabel dogImageLbl;
    private javax.swing.JLabel growScoreLbl;
    private javax.swing.JLabel manageScoreLbl;
    private javax.swing.JButton resetScoreBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel totalScoreLbl;
    // End of variables declaration//GEN-END:variables
}
