/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ncirl.oop.groupca;

import com.ncirl.oop.groupca.thomas.ScoreWindow.ScoreGUI;

/**
 *
 * @author anton
 */
public class OOPGroupCAGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OOPGroupCAGUI.class.getName());

    /**
     * Creates new form OOPGroupCAGUI
     */
    public OOPGroupCAGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        growFoodGameBtn = new javax.swing.JButton();
        deliverFoodNameBtn = new javax.swing.JButton();
        supplyFoodGameBtn = new javax.swing.JButton();
        showScoreBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OOP Group Project");
        setSize(new java.awt.Dimension(400, 300));

        growFoodGameBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_icons/seedling.png"))); // NOI18N
        growFoodGameBtn.setText("Grow Food");
        growFoodGameBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        growFoodGameBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/small_icons/arrow_right.png"))); // NOI18N
        growFoodGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                growFoodGameBtnActionPerformed(evt);
            }
        });

        deliverFoodNameBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_icons/truck.png"))); // NOI18N
        deliverFoodNameBtn.setText("Deliver Food");
        deliverFoodNameBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deliverFoodNameBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/small_icons/arrow_right.png"))); // NOI18N
        deliverFoodNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverFoodNameBtnActionPerformed(evt);
            }
        });

        supplyFoodGameBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_icons/wrench.png"))); // NOI18N
        supplyFoodGameBtn.setText("Supply Food");
        supplyFoodGameBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supplyFoodGameBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/small_icons/arrow_right.png"))); // NOI18N
        supplyFoodGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplyFoodGameBtnActionPerformed(evt);
            }
        });

        showScoreBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_icons/star.png"))); // NOI18N
        showScoreBtn.setText("Score");
        showScoreBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showScoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showScoreBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        titleLbl.setText("People Shouldn't Starve");

        exitBtn.setText("Exit");
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showScoreBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titleLbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(growFoodGameBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deliverFoodNameBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplyFoodGameBtn, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(growFoodGameBtn)
                .addGap(18, 18, 18)
                .addComponent(deliverFoodNameBtn)
                .addGap(18, 18, 18)
                .addComponent(supplyFoodGameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(showScoreBtn))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void growFoodGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_growFoodGameBtnActionPerformed
        GameLauncher.launchAlexGame();
        this.dispose();
    }//GEN-LAST:event_growFoodGameBtnActionPerformed

    private void deliverFoodNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverFoodNameBtnActionPerformed
        GameLauncher.launchAntonioGame();
        this.dispose();
    }//GEN-LAST:event_deliverFoodNameBtnActionPerformed

    private void supplyFoodGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplyFoodGameBtnActionPerformed
        GameLauncher.launchTomGame();
        this.dispose();
    }//GEN-LAST:event_supplyFoodGameBtnActionPerformed

    private void showScoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showScoreBtnActionPerformed
        ScoreGUI scoreGUI = new ScoreGUI();
        scoreGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showScoreBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose(); // Close the window
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OOPGroupCAGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deliverFoodNameBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton growFoodGameBtn;
    private javax.swing.JButton showScoreBtn;
    private javax.swing.JButton supplyFoodGameBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
