/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ncirl.oop.groupca.antonio;

import com.ncirl.oop.groupca.OOPGroupCAGUI;
import com.ncirl.oop.groupca.antonio.Items.Delivery;
import com.ncirl.oop.groupca.antonio.Items.Items;
import com.ncirl.oop.groupca.antonio.Items.Pickup;
import com.ncirl.oop.groupca.antonio.Map.Maps;
import com.ncirl.oop.groupca.antonio.Vehicle.Air;
import com.ncirl.oop.groupca.antonio.Vehicle.Land;
import com.ncirl.oop.groupca.antonio.Vehicle.Sea;
import com.ncirl.oop.groupca.antonio.Vehicle.Vehicle;
import com.ncirl.oop.groupca.thomas.GameState;
import com.ncirl.oop.groupca.thomas.util.FrameUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author anton
 */
public class AntonioGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AntonioGUI.class.getName());

    /**
     * Creates new form AntonioGUI
     */
    public AntonioGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Air = new javax.swing.JButton();
        Land = new javax.swing.JButton();
        Sea = new javax.swing.JButton();
        gameName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Food Delivery Game Menu");
        setName("Delivery_Game_Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(435, 360));
        setSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                MainMenu(evt);
            }
        });

        Air.setText("Air");
        Air.setPreferredSize(new java.awt.Dimension(80, 23));
        Air.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirActionPerformed(evt);
            }
        });

        Land.setText("Land");
        Land.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Land.setPreferredSize(new java.awt.Dimension(80, 23));
        Land.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LandActionPerformed(evt);
            }
        });

        Sea.setText("Sea");
        Sea.setPreferredSize(new java.awt.Dimension(80, 23));
        Sea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeaActionPerformed(evt);
            }
        });

        gameName.setText("Food Delivery Game Name WIP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Sea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Land, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Air, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(gameName)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(gameName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(Air, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Land, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LandActionPerformed
        // TODO add your handling code here:
        Vehicle vehicle = new Land(300, 200, 0, 0, 0, 0, 0);
        Items pickup = new Pickup(60, new int[]{150}, new int[]{200}, 0, 0);
        Items delivery = new Delivery(60, new int[]{450}, new int[]{200}, 0, 0);

        Maps map = new Maps(vehicle, pickup, delivery);
        map.createWindow();
        dispose();
    }//GEN-LAST:event_LandActionPerformed

    private void AirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirActionPerformed
        // TODO add your handling code here:
        Vehicle vehicle = new Air(300, 200, 0, 0, 0, 0, 0);
        Items pickup = new Pickup(60, new int[]{150}, new int[]{200}, 0, 0);
        Items delivery = new Delivery(60, new int[]{450}, new int[]{200}, 0, 0);

        Maps map = new Maps(vehicle, pickup, delivery);
        map.createWindow();
        dispose();
    }//GEN-LAST:event_AirActionPerformed

    private void SeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeaActionPerformed
        // TODO add your handling code here:
        Vehicle vehicle = new Sea(300, 200, 0, 0, 0, 0, 0);
        Items pickup = new Pickup(60, new int[]{150}, new int[]{200}, 0, 0);
        Items delivery = new Delivery(60, new int[]{450}, new int[]{200}, 0, 0);

        Maps map = new Maps(vehicle, pickup, delivery);
        map.createWindow();
        dispose();
    }//GEN-LAST:event_SeaActionPerformed

    private void MainMenu(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_MainMenu
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to return to the main menu?", "Confirm", JOptionPane.YES_NO_OPTION) == 1) {
            return;
        }

        GameState.resetState();

        OOPGroupCAGUI mainMenu = new OOPGroupCAGUI();
        mainMenu.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainMenu

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AntonioGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Air;
    private javax.swing.JButton Land;
    private javax.swing.JButton Sea;
    private javax.swing.JLabel gameName;
    // End of variables declaration//GEN-END:variables
}
