/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ncirl.oop.groupca.antonio;

import com.ncirl.oop.groupca.OOPGroupCAGUI;
import com.ncirl.oop.groupca.antonio.Items.Delivery;
import com.ncirl.oop.groupca.antonio.Items.Items;
import com.ncirl.oop.groupca.antonio.Items.Pickup;
import com.ncirl.oop.groupca.antonio.Map.Maps;
import com.ncirl.oop.groupca.antonio.Vehicle.Air;
import com.ncirl.oop.groupca.antonio.Vehicle.Land;
import com.ncirl.oop.groupca.antonio.Vehicle.Sea;
import com.ncirl.oop.groupca.antonio.Vehicle.Vehicle;
import com.ncirl.oop.groupca.thomas.ImageLoader;
import com.ncirl.oop.groupca.thomas.shared.CustomisationManager;

import javax.swing.JOptionPane;
import java.awt.*;

/**
 *
 * @author anton
 */
public class AntonioGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AntonioGUI.class.getName());

    /**
     * Creates new form AntonioGUI
     */
    Image ASSET;
    public AntonioGUI() {
        if(CustomisationManager.getHat() != 0){
            ASSET = ImageLoader.loadWithSize("/hats/" + CustomisationManager.getHat() + ".png", 40, 40);
        }
        initComponents();
        setLocationRelativeTo(null);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Air = new javax.swing.JButton();
        Land = new javax.swing.JButton();
        Sea = new javax.swing.JButton();
        gameName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Food Delivery Game Menu");
        setName("Delivery_Game_Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(435, 360));
        setSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                MainMenu(evt);
            }
        });

        Air.setText("Air");
        Air.setPreferredSize(new java.awt.Dimension(80, 23));
        Air.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirActionPerformed(evt);
            }
        });

        Land.setText("Land");
        Land.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Land.setPreferredSize(new java.awt.Dimension(80, 23));
        Land.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LandActionPerformed(evt);
            }
        });

        Sea.setText("Sea");
        Sea.setPreferredSize(new java.awt.Dimension(80, 23));
        Sea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeaActionPerformed(evt);
            }
        });

        gameName.setText("Food Delivery Game");

        jLabel1.setText("After choosing a vehicle your goal is to pick up cargo from ");

        jLabel2.setText("the white circles and deliver it to the black circles while");

        jLabel3.setText("avoiding the red obstacles ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(gameName)))
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Land, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Air, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(gameName)
                .addGap(18, 18, 18)
                .addComponent(Air, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Land, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LandActionPerformed
        // TODO add your handling code here:
//        Vehicle vehicle = new Land(300, 200, 0, 0, 0, 0, 0);
//        Items pickup = new Pickup(60, new int[]{150}, new int[]{200}, 0);
//        Items delivery = new Delivery(60, new int[]{450}, new int[]{200}, 0);
//        Obstacle obstacle = new Obstacle(100, 100, 50, 50);
//
//        Maps map = new Maps(vehicle, pickup, delivery);
//        map.createWindow();
        JOptionPane.showMessageDialog(null, "When using a land vehicle you have a maximum cargo capacity of 35 items", "Land", JOptionPane.INFORMATION_MESSAGE);
        Vehicle vehicle = new Land(300, 200, 55, 35, 0.0, 0.0, 0, ASSET, CustomisationManager.getBodyCol());
        Items pickup = new Pickup(60, 150, 200, 0);
        Items delivery = new Delivery(60, 450, 200, 0);

        Maps map = new Maps(vehicle);
        map.createWindow();
        dispose();
    }//GEN-LAST:event_LandActionPerformed

    private void AirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirActionPerformed
        // TODO add your handling code here:
//        Vehicle vehicle = new Air(300, 200, 0, 0, 0, 0, 0);
//        Items pickup = new Pickup(60, new int[]{150}, new int[]{200}, 0);
//        Items delivery = new Delivery(60, new int[]{450}, new int[]{200}, 0);
//        Obstacle obstacle = new Obstacle(100, 100, 50, 50);
//
//        Maps map = new Maps(vehicle, pickup, delivery);
//        map.createWindow();
        JOptionPane.showMessageDialog(null, "When using an air vehicle you have a slower acceleration when landed", "Air", JOptionPane.INFORMATION_MESSAGE);
        Vehicle vehicle = new Air(300, 200, 60, 40, 0.0, 0.0, 0, ASSET, CustomisationManager.getBodyCol());
        Items pickup = new Pickup(60, 150, 200, 0);
        Items delivery = new Delivery(60, 450, 200, 0);

        Maps map = new Maps(vehicle);
        map.createWindow();
        dispose();
    }//GEN-LAST:event_AirActionPerformed

    private void SeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeaActionPerformed
        // TODO add your handling code here:
//        Vehicle vehicle = new Sea(300, 200, 0, 0, 0, 0, 0);
//        Items pickup = new Pickup(60, new int[]{150}, new int[]{200}, 0);
//        Items delivery = new Delivery(60, new int[]{450}, new int[]{200}, 0);
//        Obstacle obstacle = new Obstacle(100, 100, 50, 50);
//
//        Maps map = new Maps(vehicle, pickup, delivery);
//        map.createWindow();
        JOptionPane.showMessageDialog(null, "When using a seafaring vessel encountering an obstacle makes you rebound further", "Sea", JOptionPane.INFORMATION_MESSAGE);
        Vehicle vehicle = new Sea(400, 300, 50, 50, 0, 0, 0, ASSET, CustomisationManager.getBodyCol());
        Items pickup = new Pickup(60, 150, 200, 0);
        Items delivery = new Delivery(60, 450, 200, 0);

        Maps map = new Maps(vehicle);
        map.createWindow();
        dispose();
    }//GEN-LAST:event_SeaActionPerformed

    private void MainMenu(java.awt.event.WindowEvent evt) {
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to return to the main menu?", "Confirm", JOptionPane.YES_NO_OPTION) == 1) {
            return;
        }

        OOPGroupCAGUI mainMenu = new OOPGroupCAGUI();
        mainMenu.setVisible(true);

        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AntonioGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Air;
    private javax.swing.JButton Land;
    private javax.swing.JButton Sea;
    private javax.swing.JLabel gameName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
